[package]
name = "pancakestack"
version = "0.1.0"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2018"

[dependencies]
"regex" = "*"
"lazy_static" = "*"
"unicode-segmentation" = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
